default:
  # Default settings for monitors
  BRIGHTNESS: 100
  MONITORS:
    eDP-1:
      WIDTH: 1920
      HEIGHT: 1080
      REFRESH_RATE: 165

commands:
  global:
    - powerprofilesctl set {POWER_PROFILE}
    - brightnessctl s {BRIGHTNESS}%

retrieve_commands:
  BRIGHTNESS: brightnessctl -m | awk -F, '{print $4}' | awk -F% '{print $1}'
  POWER_PROFILE: powerprofilesctl get

profiles:
  powersave:
    priority: 0
    POWER_PROFILE: power-saver
    BRIGHTNESS: 20
    MONITORS:
      eDP-1:
        WIDTH: 1920
        HEIGHT: 1080
        REFRESH_RATE: 60

  balanced:
    priority: 1
    POWER_PROFILE: balanced
    BRIGHTNESS: 100
    MONITORS:
      eDP-1:
        WIDTH: 1920
        HEIGHT: 1080
        REFRESH_RATE: 165

  performance:
    priority: 2
    POWER_PROFILE: performance
    BRIGHTNESS: 100
    MONITORS:
      eDP-1:
        WIDTH: 1920
        HEIGHT: 1080
        REFRESH_RATE: 165
